title: "Language-Codec: Reducing the Gaps Between Discrete Codec Representation and Speech Language Models"
# description: Xulong Zhang

theme: jekyll-theme-cayman

github:
  repository_url: https://github.com/MobileSpeech/
